services:
  neo4j:
    image: neo4j:5
    container_name: ddkg-lite
    ports:
      - "7474:7474" # Browser
      - "7687:7687" # Bolt (Python)
    environment:
      - NEO4J_AUTH=neo4j/neo4j_134
      # Using the specific quoting for reliability
      - 'NEO4JLABS_PLUGINS=[\"apoc\"]'
      - 'NEO4J_PLUGINS=[\"apoc\"]'
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - ./neo4j_lite_data:/data
      - ./outputs/phase2/graph:/import
      - ./plugins:/plugins